import Head from 'next/head'
import Header from '../components/Header'

export default function Home() {
  return (
    <div>
      <Head>
        <title>LinkUPB</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    <Header />
    <main className='flex justify-center gap-x-5 px-4 sm:px-12'>
      <div className='flex flex-col md:flex-row gap-x-5'>

      </div>
    </main>
    </div>
  );
}
